/* Execution Plan: Roadmap generated by a database on how it will execute your query step by step.
=> In SQL Server, we will have 3 plans:
	1. Estimated Execution Plan (Ctrl + L): Predicts the execution plan without executing the query.
	2. Actual Execution Plan (Ctrl + M): Shows the execution plan as it occured after running the query.
	3. Live Execution Plan: Shows the real time execution flow as the query runs. 

=> Estimate vs Actual Plans:
	- If the predictions don't match the Actual Execution Plan, this indicate issues like inaccurate statistics or outdated indexes, leading to poor performance. 
	
=> Join Algorithms: 
	- Nested Loops: Compares tables row by row; best for small tables.
	- Hash Match: Matches rows using a hash table; best for large tables.
	- Merge Join: Merge two sorted tables; efficient when both are sorted.

*/

SELECT 
	d.EnglishProductName ProductName,
	SUM(s.SalesAmount) Total_Sales
FROM FactResellerSales s
JOIN DimProduct d
ON s.ProductKey = d.ProductKey
GROUP BY d.EnglishProductName

/* SQL Hints: At the end of the query, we can add a SQL hint to say the server to do the work as you desired.
OPTION (HASH JOIN) = Used to force the server to use Hash Join. 
WITH (FORCESEEK) = Forcing the server to seek the table instead of scan.
WITH (INDEX(Index_Name)) = Forcing to use the particular index.